### PR TITLE
add a sign in demo data to improve the size of the sign

### PR DESCRIPTION
**Pull request by lucienicolier**

### CODE REVIEW

**Comment by lucienicolier** [comment]
@3nids I don't get the mistake....

**Comment by 3nids** [comment]
since you are adding a new frame and a new sign, the test checking the view (for next/previous frame/signs) does not work anymore (test: https://github.com/opengisch/signalisation_verticale/blob/master/test/test_view_sign_symbol.py#L23-L38)

either:
  
  1. fix the test according to your data
  2. do not insert new sign/frame, just change the sign_type on an exisiting one
  3. create a new set of data on another support

**Comment by 3nids** [comment]
2 or 3 sounds easier

**Comment by 3nids** [comment]
just wait a bit, I am separating the demo data from test data
you should be free to modify what you want after this

**Comment by lucienicolier** [comment]
so I delete this branch and take yours?

**Comment by 3nids** [comment]
wailt, I'll forward your changes whenever #23 is merged

**Comment by 3nids** [comment]
superseded by #25

**Pull request closed without merging**
