### PR TITLE
add attributes to join frame, sign and support

### PR DESCRIPTION
**Pull request by lucienicolier**

### CODE REVIEW

**Review by 3nids — COMMENTED** [review]
foreign key constraints are missing

**Comment by lucienicolier** [comment]
@3nids I don't get why it is not finding siro_od.frame

**Comment by 3nids** [comment]
the tables were not created in correct order, fixed in 38b9b6f

**Review by 3nids — APPROVED** [review]

**Comment by lucienicolier** [comment]
nice, thanks

**Pull request merged**
